### ISSUE TITLE
New Mali GPU r4p1 causes issues

### ISSUE THREAD

**Issue by steeve** [codesnake/linux-amlogic#13]
With this new driver, Kodi fails to initialize its main window, and thus fails to start

Tested on CX-S859 (meson8b).

**Comment by kszaq** [comment]
Works fine for me on MK808B Plus (also meson8b). Do you use updated binaries?

**Comment by steeve** [comment]
I seem, yes. Built from https://github.com/surkovalex/OpenELEC.tv@91e8eb08619ebf811676ae5a710b973215f8cb62

**Comment by steeve** [comment]
According to https://github.com/surkovalex/OpenELEC.tv/commit/9031e8bdd5381df1341e7c88dbd666c06d6f560b I am

**Comment by kszaq** [comment]
This is for meson6, meson8b uses opengl-meson8. You need to pick this one: https://github.com/kszaq/OpenELEC.tv/commit/6b90bbc4d3001b4abd878abdaf5d4dfacb3d9968 or wait for Codesnake to update meson8 binaries as well.

**Comment by steeve** [comment]
Ah good one! By the way, do you plan to merge your fork into codesnake's at some point ?
Because I'm starting to see significant differences between all the forks.

By the way, nice fork. I have a MK808B myself, I'm gonna test it for sure :)

**Comment by steeve** [comment]
Closing, btw
