### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by Raxone** [codesnake/linux-amlogic#26]
I got big problem with change mtd partitions size number etc i think about nftl nand logo,aml_logo,system,userdata etc.
I compile kernel and u-boot for AML-8726 and everthing work but i don't now how to change.
Is that possible or that hardcoded or something else?
And if is possibile please some help.
Thanks.

**Comment by codesnake** [comment]
NAND partitions are defined in device tree. You can change it there, just make sure both your system and recovery use the same partition layout.

**Comment by Raxone** [comment]
Thanks for fast reply.
Problem is in kernel config i just turn of option to read u-boot env to
cmdline in kernel boot.
